---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - admission.geoffrey.io
  resources:
  - namespaceselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admission.geoffrey.io
  resources:
  - namespaceselectors/finalizers
  verbs:
  - update
- apiGroups:
  - admission.geoffrey.io
  resources:
  - namespaceselectors/status
  verbs:
  - get
  - patch
  - update
